### ISSUE TITLE
NotImplementedError: CopyRange not supported

### ISSUE THREAD

**Issue by cool-RR** [google/orbax#1048]
See this code sample:

```python
import pathlib

import orbax.checkpoint

orbax_checkpointer = orbax.checkpoint.PyTreeCheckpointer()
tree = {'key': 7}
path = pathlib.Path(__file__).parent / 'foo'
orbax_checkpointer.save(path, tree)
```

When I run it on Linux, it works fine. When I run it on Windows 10, I get [this traceback](https://gist.github.com/cool-RR/f51c95b1dba9c26be45725cf7e767467) with the exception: `builtins.NotImplementedError: CopyRange not supported`.

The versions I use:

```
orbax-checkpoint==0.5.23
tensorstore==0.1.64
```

**Comment by cpgaffney1** [comment]
Post the issue on Tensorstore page please, this is an issue with the implementation of `experimental_copy_range_to`. I'm not surprised that you run into some issues on Windows - we've done no testing for that.

**Comment by cpgaffney1** [comment]
Also, this is probably unrelated, but maybe use etils.epath instead of pathlib? That is the library our code is tested on.

**Comment by laramiel** [comment]
While there is an underlying tensorstore issue with path comparison here, I think that using pathlib to convert the path to posix in orbax when generating the tensorstore path would be an appropriate fix.
