### ISSUE TITLE
Github releases page not up to date with pypi releases

### ISSUE THREAD

**Issue by nouiz** [google/orbax#1121]
The page https://github.com/google/orbax/releases show the last releases as 0.1.7 from March 2023.
So it sound like there isn't any releases.

But on pypi, we see there is many releases since May 2024: https://pypi.org/project/orbax-checkpoint/

Would be great if the github pages is updated or point to the pypi list. That way people will know there is frequent releases.

**Comment by cpgaffney1** [comment]
This is documented in the [README](https://github.com/google/orbax?tab=readme-ov-file#releases) but I agree it's not super obvious. I'm not aware of a way (without a lot of effort) to tag releases retrospectively so they'll start showing up, but we can at least set the tag going forward.

**Comment by orbax-dev** [comment]
Ok, this is fixed now.
