### ISSUE TITLE
Failed to get flag value for EXPERIMENTAL_ORBAX_USE_DISTRIBUTED_PROCESS_ID

### ISSUE THREAD

**Issue by ZaberKo** [google/orbax#1147]
Recently I upgraded orbax from 0.5.23 to 0.6.1, then I constantly get this message `[absl][INFO] - [thread=MainThread] Failed to get flag value for EXPERIMENTAL_ORBAX_USE_DISTRIBUTED_PROCESS_ID.` I didn't find any documentation about this env var. Is it a problem that need concerns? And how to suppress it?

Reproduction code:
- jax: 0.4.31
- orbax-checkpoint: 0.6.1

```python
import orbax.checkpoint as ocp
from pathlib import Path
import shutil
import jax.numpy as jnp

import hydra

@hydra.main(version_base=None, config_path="./configs", config_name="config")
def train(config) -> None:
    output_dir = Path("debug/tmp1").absolute()
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True)

    ckpt_options = ocp.CheckpointManagerOptions(
        save_interval_steps=2,
        max_to_keep=False,
    )
    ckpt_path = output_dir / "checkpoints"

    checkpoint_manager = ocp.CheckpointManager(
        ckpt_path,
        options=ckpt_options,
    )

    m = dict(
        a=jnp.array([1, 2, 3]),
        b=jnp.array([4, 5, 6]),
        c=jnp.array([7, 8, 9]),
    )

    checkpoint_manager.save(1, args=ocp.args.StandardSave(m))


    m = dict(
        a=jnp.array([10, 20, 30]),
        b=jnp.array([40, 50, 60]),
        c=jnp.array([70, 80, 90]),
    )
    checkpoint_manager.save(2, args=ocp.args.StandardSave(m))
    checkpoint_manager.close()

if __name__ == "__main__":
    train()
```

**Comment by orbax-dev** [comment]
Nothing to worry about, just an info log for an experimental feature. I'll reduce the frequency of the log to once to minimize this annoyance.

**Comment by ZaberKo** [comment]
> Nothing to worry about, just an info log for an experimental feature. I'll reduce the frequency of the log to once to minimize this annoyance.

I think a default value should be set to disbale it for normal users, until it is explicitly set.
