### ISSUE TITLE
Main thread blocks for a long time when using GCS paths with AsyncCheckpointer

### ISSUE THREAD

**Issue by dchen496** [google/orbax#179]
Hello, great project you guys have here! I recently started using the AsyncCheckpointer / PyTreeCheckpointHandler with GCS paths and noticed that checkpointing blocks the main thread (the one calling CheckpointManager.save()) for about ~30 seconds. During this period there is a small amount of network traffic (~30-50 kB/s) but no bulk data transfer. The bulk data transfers seem to happen after CheckpointManager.save(), as expected.

I did a bit of digging and as far as I can tell, the time is spent creating metadata files for every array in the pytree. The pytree has a couple dozen arrays and these files are created sequentially, which is slow on GCS. Would it be possible to reduce the number of these files or create them in parallel? Or is there a different workaround to save fewer files (note that I am also using sharded arrays)?

**Comment by cpgaffney1** [comment]
Hi, apologies for taking so long to respond, I should really have been checking these issues! 

Let me take a look, I've been developing some checkpointing benchmarks recently. In general, directories for each parameter should be created in parallel, while any writing within these parameter directories should happen in the non-blocking part.

**Comment by cpgaffney1** [comment]
Small update: we've built several internal benchmarks and I'm not seeing the issue you describe. It's possible (or likely) that an issue exists on GCP, we're currently investigating.

**Comment by dchen496** [comment]
Thanks for looking into this!

One piece of information that might be relevant - on GCP with TPUv4 we're kind of forced into using GCS in a different region. The TPUv4 is only available in us-central2, but almost no other GCP services are really available there (at least not without extremely low quota limits). So we end up having to do almost everything else, including storage, in us-central1. I imagine this makes the latency of metadata / small file requests much higher than it would normally be.

**Comment by cpgaffney1** [comment]
That would probably account for most of the behavior you've described. If only the TPUs are in a different region, the copy operation from device to host will take a long time between different regions. 

Assuming your hosts are in the same region as your TPUs, there's still a blocking operation to create directories for each of the parameters that are going to be saved, which can be time consuming. Tensorstore is rolling out an optimization to deal with this issue though.

**Comment by cpgaffney1** [comment]
Note that OCDBT (https://google.github.io/tensorstore/kvstore/ocdbt/index.html#ocdbt-key-value-store-driver) will also probably improve performance. Currently working on documentation for this.
