### ISSUE TITLE
Orbax does not indicate its dependency versions, which easily leads to bugs

### ISSUE THREAD

**Issue by lucaslingle** [google/orbax#224]
I am writing to point out that Orbax does not indicate its dependencies' versions. 
This led me to a bug today on a Cloud TPU.

To be more specific, the recent the Orbax 0.1.2 release uses ```from jax.sharding import Mesh```, which fails with Jax 0.3.25. If the dependency versions were indicated in the ```pyproject.toml```, pip could figure out there is a version conflict, and this out-of-the-blue error would not appear. Hope to see this addressed, given the growing importance of Orbax!

As a workaround, I have downgraded to Orbax 0.1.1.

**Comment by IvyZX** [comment]
Maybe it's worthwhile to set the requirement of JAX to be >= 0.4.1 for Orbax >= 0.1.2?

**Comment by lucaslingle** [comment]
It looks like this was fixed in an Orbax commit earlier today! Many other requirements are left open-ended, however, so I'll leave it to the authors to decide whether to close this ticket.

**Comment by lucaslingle** [comment]
Closing based on remarks [here](https://github.com/google/flax/issues/2886#issuecomment-1439177623).
