### ISSUE TITLE
Loading only a part of the saved checkpoint (i.e. only model weights)

### ISSUE THREAD

**Issue by hr0nix** [google/orbax#331]
I want to implement the following functionality:
* During training I'd like to save the whole flax TrainState object to a checkpoint so that I can use it to continue training.
* When loading a model for inference from a checkpoint, I only want to load model params, which is a subtree of the TrainState pytree.

Unfortunately, I haven't been able to figure out how to implement such partial loading in orbax. Any guidance will be much appreciated.

**Comment by qchuG** [comment]
Hi, what exactly should be in the `transformations` argument and is this documented anywhere?

**Comment by cpgaffney1** [comment]
https://orbax.readthedocs.io/en/latest/checkpointing_pytrees.html#restoring

https://orbax.readthedocs.io/en/latest/transformations.html

**Comment by qchuG** [comment]
Thank you, could you give an example for this issue? It's still not clear how to only load part of the checkpoint.

What should the `transformations` look like?

**Comment by cpgaffney1** [comment]
```
restore_args = checkpoint_utils.construct_restore_args(target_tree)
ckptr = PyTreeCheckpointer()
ckptr.restore(path, args=ocp.args.PyTreeRestore(
    target_tree, restore_args=restore_args, transforms={})
```
