### ISSUE TITLE
orbax equivalent to load_state_dict(strict=False)

### ISSUE THREAD

**Issue by sshleifer** [google/orbax#360]
I am trying to convert checkpoints to orbax format and getting a bad traceback:

```
  File "/home/sam/.conda/envs/char-latest/lib/python3.8/site-packages/orbax/checkpoint/utils.py", line 260, in _reconstruct_from_keypath
    if not isinstance(result, list) and key_name not in result:
TypeError: argument of type 'LazyValue' is not iterable
```

Higher level problem: is it possible to tell PyTreeCheckpointHandler to not load params that aren't present. like `load_state_dict(strict=False)` in pytorch?

`orbax-checkpoint==0.2.3`

**Comment by cpgaffney1** [comment]
(Assuming your specific problem is related to the higher-level problem you mention.)

This can be done using [transformations](https://orbax.readthedocs.io/en/latest/api_reference/checkpoint.transform_utils.html). If there are a number of keys in the checkpoint that you wish to _not_ load, you can just pass `transforms={}` to `PyTreeCheckpointHandler.restore`. You will also need to pass the `item` argument. Whatever the tree structure of your `item` is, that's what you'll get back - any extra keys in the checkpoint will automatically dropped. Also, if you have extra keys in `item` relative to the checkpoint, those will just get carried over into the result without being touched.

**Comment by sshleifer** [comment]
is transforms the way to cast params to fp32 after load? 

```
        items = {MS: {PARAMS: unboxed_train_state.params}}
        kw = {MS: {"restore_args": {PARAMS: restore_args.params}}}
        params = ckpt_manager.restore(
            step=ckpt_manager.latest_step(), items=items, restore_kwargs=kw
        )
```

**Comment by cpgaffney1** [comment]
No, check out RestoreArgs, there is a dtype parameter and it does casting for you.

**Comment by sshleifer** [comment]
That worked thx!
