### ISSUE TITLE
Drop unused dependencies `cached_property` and `importlib_resources`

### ISSUE THREAD

**Issue by Zac-HD** [google/orbax#361]
I recently noticed that `orbax-checkpoint` depends on the [`cached-property` package](https://pypi.org/project/cached-property/) and [`importlib-resources` backport](https://pypi.org/project/importlib-resources/), and wanted to suggest using the standard library instead (respectively [`@functools.cached_property`](https://docs.python.org/3/library/functools.html#functools.cached_property) in Python 3.8+ and the [`importlib.resources` module](https://docs.python.org/3/library/importlib.resources.html) in Python 3.7+; and note that Python 3.7 is end-of-life next week).

But then when I did a quick search to check how much work this would be... it looks like `orbax-checkpoint` _literally doesn't use these packages at all_.  So dropping them should be quite trivial, and allow for somewhat smaller virtual environments 😁

**Comment by cpgaffney1** [comment]
Thanks for pointing this out! `importlib_resources` is needed by our `etils` import - for some reason it doesn't get included automatically. The `cached_property` dependency does seem unneeded though.

**Comment by Zac-HD** [comment]
Looking at https://github.com/google/etils/blob/4a042b574ddcb6be0e0787539962f874535fb508/pyproject.toml, `etils` only has optional dependencies, so `orbax-checkpoint` should depend on `etils[epath,epy]` rather than plain `etils` + `importlib_resources`.

That way we'll automatically stop depending on the backport when `etils` drops it or makes it version-specific 🙂
