### ISSUE TITLE
make tensorflow optional orbax-export.

### ISSUE THREAD

**Issue by ethanluoyc** [google/orbax#364]
Hi,

Is it possible to make TensorFlow optional in Export?

From the other TF related repos it's quite common to make TensorFlow optional as the user can choose between different TF versions (e.g., tensorflow-cpu, tensorflow-macos).

Created #365

**Comment by ajain-23** [comment]
Thanks for the suggestion! This has been added in https://github.com/google/orbax/commit/7b826cb14e51ea3d87c01c020a04234698b19d8f.
