### ISSUE TITLE
orbax-export does not support arbitrary nested observations

### ISSUE THREAD

**Issue by ethanluoyc** [google/orbax#371]
Hi,

It seems that orbax.export currently only supports functions of the form  `fn(params, x)` where x is `Mapping[str, Array]`, is that correct? I have use cases in models where `x` can have multiple levels of nesting.

What would be the best approach for handling this with orbax. I found that I can save a SavedModel via a naive approach by tf.function tracing but somehow it fails with orbax. I am not entirely sure what the issue that's causing this.

**Comment by maxwillzq** [comment]
I didn't any limitation on `x` of  `fn(params,x)`. So it should be `PyTree` in general. 
Could you provide some code examples ? 
Thanks

**Comment by ethanluoyc** [comment]
Thanks for the reply!

I am specifically looking at the following use case.

```python
def model_fn(params, x):
    return jnp.sum(params["w"]) + jnp.sum(x["a"]['b'])

key = jax.random.PRNGKey(0)

params = {"w": jnp.zeros((3, 3))}

jax_module = orbax.export.JaxModule(
    params,
    model_fn,
    trainable=False,
    input_polymorphic_shape=None,
)


dummy_inputs = {"a": {'b': jnp.zeros(3)}}

input_signature = jax.tree_map(
    lambda x: tf.TensorSpec(dtype=x.dtype, shape=x.shape),
    dummy_inputs
)

save_model_path = "saved_model"

manager = orbax.export.ExportManager(
    jax_module,
    [
        orbax.export.ServingConfig(
            "serving_default",
            input_signature=[input_signature],
            tf_postprocessor=lambda x: dict(output=x),
        ),
    ],
)
print(manager.serving_signatures)

manager.save(save_model_path)
loaded = tf.saved_model.load(save_model_path)
loaded.signatures["serving_default"](**dummy_inputs)

```

**Comment by maxwillzq** [comment]
There are some weired behavior in before and after tf. SavedModel.save/load. 

```
{'serving_default': <ConcreteFunction inference_fn(arg1) at 0x7F69E170E020>}
Before tf.SavedModel: tf.function signature is  (({'a': {'b': TensorSpec(shape=(3,), dtype=tf.float32, name='preprocessed_inputs_0_a_b')}},), {})
After tf.SavedModel: tf.function signature is  ((), {'preprocessed_inputs_0': TensorSpec(shape=(3,), dtype=tf.float32, name='preprocessed_inputs_0')})
```

So the tf concrete function input signature was changed for your nested data structure.  You can use the new signature to run the loaded function.

Why this happens ? I have no idea what happen under tf.SavedModel.save/load.

**Comment by ethanluoyc** [comment]
I have no idea what is going on either. This looks like a bug in SavedModel to me.

I came across this https://github.com/tensorflow/tensorflow/issues/40501#issuecomment-669187477 when I was investigating, could this be related? `orbax.export` passes the input signature to `tf.function` which is similar to the issue they describe there.

https://github.com/google/orbax/blob/main/export/orbax/export/serving_config.py#L273

**Comment by voutcn** [comment]
Because the signature will flatten all the inputs. If you want to preserve the input args/kwargs, you need to load attach the function to the module and reload it as a python object.

```python
 manager.tf_module.__call__ = manager.serving_signature['serving_default']

manager. save(save_model_path)
loaded = tf.saved_model.load(save_model_path)
result = loaded(dummy_inputs)
```

**Comment by maxwillzq** [comment]
https://github.com/google/orbax/pull/380 solve this problem by @voutcn.    @ethanluoyc , FYI.
Please help verify it. Thanks a lot

**Comment by ethanluoyc** [comment]
I can confirm it works now. Many thanks! @maxwillzq @voutcn !

**Comment by maxwillzq** [comment]
Please help close it. Thanks
