### ISSUE TITLE
Restore latest checkpoint

### ISSUE THREAD

**Issue by gianlucadetommaso** [google/orbax#374]
Hello,
is there available functionality to restore the latest checkpoint stored in a directory? I'm looking for something analogous to [flax.checkpoints.latest_checkpoint](https://flax.readthedocs.io/en/latest/api_reference/flax.training.html#flax.training.checkpoints.latest_checkpoint). In particular, I would like to obtain the path to the latest checkpoint in a given directory.

Currently it is not super clear to me what happens when I pass a directory to `CheckpointManager.restore`. Do I automatically get the latest checkpoint? If so, is there a way to access its path?

Thanks!

**Comment by cpgaffney1** [comment]
See https://orbax.readthedocs.io/en/latest/api_reference/checkpoint.checkpoint_manager.html#id1. `CheckpointManager.restore` requires that you pass a step, and it provides methods to help you get all current steps, latest step, or best step according to some metric.

**Comment by gianlucadetommaso** [comment]
Thanks, I had missed it!
