### ISSUE TITLE
ModuleNotFoundError: No module named 'jax.experimental.gda_serialization'

### ISSUE THREAD

**Issue by gianlucadetommaso** [google/orbax#393]
Hi,
[this line](https://github.com/google/orbax/blob/c7a7fd48ff094ac4167d3fb1c10f8b6c8de32b3a/checkpoint/orbax/checkpoint/type_handlers.py#L25) throws the error in the title with the latest version of JAX (0.4.13).

**Comment by Wolfboyccc** [comment]
Has this problem been resolved? If yes, how was it resolved?

**Comment by luna-yan** [comment]
Hi , I've meet the same issue with saycan-robot-pick-place jupyter code. 
ModuleNotFoundError: No module named 'jax.experimental.gda_serialization'

**Comment by Wolfboyccc** [comment]
My solution is to downgrade the version of JAX. You can try several versions. That's indeed a version issue
