### ISSUE TITLE
Checkpointing fails if a key includes a forward slash

### ISSUE THREAD

**Issue by langosco** [google/orbax#422]
To reproduce:

```python
import orbax.checkpoint

CHECKPOINT_DIR = "./checkpoints"
checkpointer = orbax.checkpoint.PyTreeCheckpointer()
tree = {"test/test": 42}
checkpointer.save(CHECKPOINT_DIR, tree)
```
Raises
```
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints.orbax-checkpoint-tmp-1690216561285472/test/test'
```

This is a problem in particular for haiku parameter names, which can include forward slashes by default.

**Comment by cpgaffney1** [comment]
Can't reproduce your issue on a public colab. Please make sure you're using the latest version of the orbax-checkpoint package. Full support for haiku style paths was added not that long ago, so you might have an old version.

**Comment by langosco** [comment]
You're right, I have orbax version 0.2.3. However it looks like `pip install --upgrade orbax-checkpoint` doesn't install the newer version―is it possible that the newer orbax versions don't support python 3.8?
