### ISSUE TITLE
Running orbax from an existing asyncio event loop

### ISSUE THREAD

**Issue by hr0nix** [google/orbax#481]
Currently, the checkpoint loading code calls `asyncio.run` even when the synchronous checkpointer impl is being used. This is problematic when calling `orbax` from within an existing asyncio event loop, because this method cannot be called within an existing loop and the existing loop should be reused instead. Having an existing event loop seems to be a relatively common scenario when running within a webserver or, say, from jupyter, so it probably needs to be addressed.

**Comment by hr0nix** [comment]
> you want it supported in more cases than just ipython?
I discovered the problem when trying to use orbax from within an asyncio-based web server

**Comment by cpgaffney1** [comment]
Ok thanks for reporting, this shouldn't be hard to enable.

**Comment by cpgaffney1** [comment]
Forgot to update this thread - this should be working by default by now, `nest_asyncio` is applied whenever there is a running event loop. Let us know if it's still not working for you.
