### ISSUE TITLE
Best practice for tracking the best *and* latest?

### ISSUE THREAD

**Issue by allen-adastra** [google/orbax#526]
Hello!

From my understanding, it seems that when you provide a `best_fn` to `CheckpointManagerOptions`, it no longer saves checkpoints based off recency.

What if I want to save checkpoints based off both "goodness" and recency? It seems one way to do that is to have two instances of `CheckpointManager`, but that seems inelegant... surely it should be possible to have only one right?

**Comment by cpgaffney1** [comment]
You're right that providing `best_fn` can result in more recent checkpoints getting deleted if they have a worse score. There's some other options you could use though - `keep_time_interval` should allow you to preserve checkpoints at a certain time interval, say one per hour. `keep_period` is similar - it forces preserving checkpoints with the given period. 

Unfortunately the option you would seem to be looking for would be something like `preserve_last_n` which will avoid deleting the last n checkpoints no matter what their metrics score, but we don't have support for that at the moment. Perhaps you could hack it by using `keep_checkpoints_without_metrics=True` and then avoiding populating the metrics for recent checkpoints until you're ok with potentially deleting them.
