### ISSUE TITLE
Issue loading checkpoint step during Paxml evaluation

### ISSUE THREAD

**Issue by ashors1** [google/orbax#575]
I am attempting to run evaluation after training a model in [Paxml](https://github.com/google/paxml). When trying to locate the step of the latest checkpoint, I see this error: 
```
 File "/opt/paxml/paxml/eval_lib.py", line 482, in evaluate
    _common_eval_or_decode_loop(
 File "/opt/paxml/paxml/eval_lib.py", line 817, in _common_eval_or_decode_loop
    last_checkpoint_step = int(
ValueError: invalid literal for int() with base 10: 'PLACEHOLDER://step'
```
I have tracked down the issue in Paxml to [this commit](https://github.com/google/paxml/commit/62be5fab9cb9a5d8846bee49af47e981e7b880d0), but we believe this failure is a result of an underlying Orbax bug.

**Comment by chandrasekhard2** [comment]
Hi @rxsang , can you take a look?

**Comment by cpgaffney1** [comment]
Could you update to the latest version of `orbax-checkpoint`? I would suspect this is the issue.
