### ISSUE TITLE
save_args_from_target alternatives?

### ISSUE THREAD

**Issue by haohuanw** [google/orbax#722]
i've been seeing warning messages on using `save_args_from_target`:

```
W0220 14:01:27.856204 687591 type_handlers.py:399] SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before May 1st, 2024.
```

checked flax page https://flax.readthedocs.io/en/latest/guides/converting_and_upgrading/orbax_upgrade_guide.html and the content is not yet updated. Is there a TLDR on how user should change the checkpointing code before i dig into other documents? is https://orbax.readthedocs.io/en/latest/api_refactor.html suppose to be the example that i should follow?

**Comment by cpgaffney1** [comment]
Conceptually you would want to follow the Flax guide, and then follow the API Refactor guide in sequence. Probably unless your use case is more complicated, you can just follow the basic docs https://orbax.readthedocs.io/en/latest/orbax_checkpoint_101.html. I'll talk to the Flax folks about updating that guide for Orbax's newer API.

**Comment by haohuanw** [comment]
thanks! i took a stab on trying it out and i want to make sure this is something correct before flax folks update their tutorial:

consider i have something like this:

```
state: flax.train_state.TrainState
metadata: Mapping[str, Any]
```

Saving:

```
checkpoint_manager.save(step, args=ocp.args.Composite(
     state=ocp.args.StandardSave(state),
     metadata=ocp.args.JsonSave(metadata),
))
checkpoint_manager.wait_until_finished()
```

Restoring:

```
state = create_empty_state()
restored_args = checkpoint_manager.restore(
    step, args=ocp.args.Composite(
       state=ocp.args.StandardRestore(),
       metadata=ocp.args.JsonRestore(),
))
metadata = restored_args.metadata
state.replace(**restored_args.state)
```

also, it looks like `SaveArgs.aggregate` is it basically now handled by pytree / standard handler already?

**Comment by cpgaffney1** [comment]
For restore, you should probably do:

```
# This is better, otherwise the empty state consumes real memory, and is unnecessary. Ultimately up to you though
# tree of jax.ShapeDtypeStruct
# Make sure the leaves have the `sharding` property set
abstract_state = create_abstract_state()
restored = checkpoint_manager.restore(
    step, args=ocp.args.Composite(
       # Provide the target as a reference
       state=ocp.args.StandardRestore(abstract_state),
       metadata=ocp.args.JsonRestore(),
))
metadata = restored.metadata
state = restored.state
```

`aggregate` is essentially obsolete at this point, so you can safely ignore it.

**Comment by haohuanw** [comment]
sounds good thanks!
