### ISSUE TITLE
CheckpointManager with a dataclass containing strings

### ISSUE THREAD

**Issue by LeonEricsson** [google/orbax#825]
I'm trying to migrate over to the new CheckpointManager but having some trouble. In the Legacy API, the below code works fine. Where t_state is a TrainState and config is a custom flax dataclass containing int's, strings, etc.

```

orbax_checkpointer = ocp.PyTreeCheckpointer()
options = ocp.CheckpointManagerOptions(
    max_to_keep=config.checkpoints_to_keep,
    create=True,
)
mgnr = ocp.CheckpointManager(
        ckpt_dir,
        orbax_checkpointer,
        options=options,
    )

config = Config()
ckpt = {'train_state': state, 'config': config}
mngr.save(0, ckpt)

```
but when I try to refactor the code according to https://orbax.readthedocs.io/en/latest/api_refactor.html. I get an error when trying to save the Config object. I've attempted to use CheckpointArgs (ocp.args) StandardSave and JsonSave but both give me an error:

`ValueError: Unsupported type: <class 'str'> for key: ('env_id',).`

I was expecting this to work because as I said Config is a flax.struct.dataclass

**Comment by cpgaffney1** [comment]
`StandardSave` doesn't support strings, but `JsonSave` should work.... `ocp.args.PyTreeSave` should also work in theory. Can you paste your new code that's giving the error?

**Comment by LeonEricsson** [comment]
Thanks for the quick reply, here is the code.

```
from flax import struct
import orbax.checkpoint as ocp

@struct.dataclass
class Config:
    env_id: str = 'test'
    seed: int = 0
    max_num_iters: int = 800
    num_channels: int = 128
    num_layers: int = 6
    resnet_v2: bool = True
    selfplay_batch_size: int = 1024
    num_simulations: int = 32
    max_num_steps: int = 256
    training_batch_size: int = 4096
    lr_init: float = 0.0005
    lr_end: float = 0.00001
    lr_steps: int = 400
    weight_decay: float = 3e-5
    eval_interval: int = 5
    eval_past_agents: bool = False
    num_eval_opponents: int = 2
    num_eval_simulations: int = 32
    name: str = None

config = Config()

options = ocp.CheckpointManagerOptions()
mngr = ocp.CheckpointManager(ckpt_dir, item_names=('model', 'config'), options=options)

mngr.save(0, args=ocp.args.Composite(
    model=ocp.args.StandardSave(state),
    config=ocp.args.JsonSave(config))
    )
```
Tried PyTreeSave and got the same error. This is on `orbax-checkpoint==0.5.7`

**Comment by cpgaffney1** [comment]
Ran that code, excluding the `model=ocp.args.StandardSave(state)` and it tells me `config` is not JSON serializable (because it's a flax.struct.dataclass, not a JSON object). 

I used PyTreeSave instead of JsonSave and it works.

**Comment by LeonEricsson** [comment]
Strange. I definitely got the same error using PyTreeSave. I'll test it again. What version were you running?

**Comment by cpgaffney1** [comment]
Ah this was running in a colab, so must be latest (0.5.9).

**Comment by LeonEricsson** [comment]
I think I have to run 0.5.7 but I'll check. Thanks for the help anyway
