### ISSUE TITLE
"SaveArgs.aggregate is deprecated" warning for empty tuples and empty NamedTuples

### ISSUE THREAD

**Issue by jaro-sevcik** [google/orbax#980]
Saving empty tuples or empty NamedTuples newly results in a deprecation warning. This is particularly annoying for `optax.EmptyState()` (which is an empty NamedTuple) because it is often present in checkpoints. Is there a workaround for this regression?

Repro (with orbax 0.5.20):
```python
import orbax.checkpoint as ocp
import jax
import os
from typing import NamedTuple

path = '/tmp/my-checkpoints/'
os.makedirs(path, exist_ok=True)

class X(NamedTuple):
    pass

my_tree = { 'a': X() }
checkpointer = ocp.AsyncCheckpointer(ocp.StandardCheckpointHandler())
checkpointer.save(path + '/checkpoint_name', args=ocp.args.StandardSave(my_tree), force=True)
```
Running this program will result in the warning below:
```
WARNING:absl:SaveArgs.aggregate is deprecated, please use custom TypeHandler (https://orbax.readthedocs.io/en/latest/custom_handlers.html#typehandler) or contact Orbax team to migrate before August 1st, 2024.
```

An ordinary empty tuple will produce the same warning:
```python
...
my_tree = { 'a': () }
checkpointer = ocp.AsyncCheckpointer(ocp.StandardCheckpointHandler())
checkpointer.save(path + '/checkpoint_name', args=ocp.args.StandardSave(my_tree), force=True)
```

Is there a reason for excluding tuples from the machinery for [saving and restoring empty values](https://github.com/google/orbax/blob/f694fe8eb3b19f2e92e5abe764744ca2bab5fb30/checkpoint/orbax/checkpoint/type_handlers.py#L94)?

**Comment by cpgaffney1** [comment]
It's just an artifact of the implementation - this is not intentional and apologies for the annoyance. I'm working on a larger change where you would no longer see this message, as it's actually more difficult than you would expect to fix this message alone, and not worth it given the larger change I'm working on. Hoping to have it submitted within a few business days.
